services:
  pipeline:
    image: pgc-images.sbgenomics.com/rokita-lab/tapestry:latest
    platform: linux/amd64
    environment:
      - .env
    working_dir: /app
    command: >
      bash -c "
        python -m db.migrate &&
        python -m pipelines.01_histologies &&
        python -m pipelines.02_tej &&
        python -m pipelines.03_tej_cpm &&
        python -m pipelines.05_gene_junction_summary.py &&
        python -m pipelines.status &&
        python -m pipelines.refresh_views
      "
    volumes:
      - .:/app
      - ./data:/app/data:ro
